import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">  
    <body className={inter.className}>
    <main className={styles.main+ " dark text-foreground bg-background"}>
    <div className={styles.description}>
    <p>Alumnos sin acceder a plataforma Esiapi </p>
    <div>
    <a rel="noopener noreferrer" href="/">Inicio</a>
    </div>
    </div>
    </main>
    {children}
    </body>
    </html>
  );
}
